import { buildCaseInsensitiveLookup, type CaseInsensitiveLookup } from "./case-insensitive-lookup";

/**
 * Nomes reais de `enum e_job` (`rathena/src/common/mmo.hpp:888-1113`), sem o
 * prefixo `JOB_` — extraídos com
 * `sed -n '888,1113p' rathena/src/common/mmo.hpp | grep -oE "JOB_[A-Z0-9_]+" | sort -u`,
 * excluindo os 4 marcadores de faixa que não são classe jogável
 * (`JOB_MAX`, `JOB_MAX_BASIC`, `JOB_SECOND_JOB_START`, `JOB_SECOND_JOB_END`).
 * 194 nomes, não ~600 (a contagem real do enum, não uma estimativa).
 *
 * `JobDatabase::parseBodyNode` (`rathena/src/map/pc.cpp:13819-13831`) monta
 * `"JOB_" + job_name` e resolve via `script_get_constant` pra cada chave de
 * `Jobs:` em `job_stats.yml` — um nome que não bate com nenhum destes NÃO é
 * rejeitado ali (aquele `if` é gracioso), mas derruba o map-server inteiro
 * mais adiante com `terminate called ... check failed: ch != NONE`
 * (achado real, Fase 3.3, `docs/audit/fase3-testes/FASE3.3-FECHAMENTO.md`).
 * `JobClassSchema.name`/`RawJobStatsSchema` nunca validaram contra isso —
 * esta lista existe pra fechar esse buraco ANTES do YAML ser escrito.
 *
 * Case-insensitive por `buildCaseInsensitiveLookup` (`case-insensitive-
 * lookup.ts`) — mesma infra já usada pra Skills/Status, porque
 * `script_get_constant` resolve por `strcasecmp` (`"Swordman"` casa com
 * `JOB_SWORDMAN`), não igualdade exata.
 */
export const RATHENA_JOB_NAMES: readonly string[] = [
  "ABYSS_CHASER",
  "ACOLYTE",
  "ACOLYTE_HIGH",
  "ALCHEMIST",
  "ARCHBISHOP_2ND",
  "ARCHER",
  "ARCHER_HIGH",
  "ARCH_BISHOP",
  "ARCH_BISHOP_T",
  "ARCH_MAGE",
  "ASSASSIN",
  "ASSASSIN_CROSS",
  "BABY",
  "BABY_ACOLYTE",
  "BABY_ALCHEMIST",
  "BABY_ARCHER",
  "BABY_ARCH_BISHOP",
  "BABY_ASSASSIN",
  "BABY_BARD",
  "BABY_BLACKSMITH",
  "BABY_CRUSADER",
  "BABY_CRUSADER2",
  "BABY_DANCER",
  "BABY_GENETIC",
  "BABY_GUILLOTINE_CROSS",
  "BABY_GUNSLINGER",
  "BABY_HUNTER",
  "BABY_KAGEROU",
  "BABY_KNIGHT",
  "BABY_KNIGHT2",
  "BABY_MAGE",
  "BABY_MECHANIC",
  "BABY_MECHANIC2",
  "BABY_MERCHANT",
  "BABY_MINSTREL",
  "BABY_MONK",
  "BABY_NINJA",
  "BABY_OBORO",
  "BABY_PRIEST",
  "BABY_RANGER",
  "BABY_RANGER2",
  "BABY_REBELLION",
  "BABY_ROGUE",
  "BABY_ROYAL_GUARD",
  "BABY_ROYAL_GUARD2",
  "BABY_RUNE_KNIGHT",
  "BABY_RUNE_KNIGHT2",
  "BABY_SAGE",
  "BABY_SHADOW_CHASER",
  "BABY_SORCERER",
  "BABY_SOUL_LINKER",
  "BABY_SOUL_REAPER",
  "BABY_STAR_EMPEROR",
  "BABY_STAR_EMPEROR2",
  "BABY_STAR_GLADIATOR",
  "BABY_STAR_GLADIATOR2",
  "BABY_SUMMONER",
  "BABY_SURA",
  "BABY_SWORDMAN",
  "BABY_TAEKWON",
  "BABY_THIEF",
  "BABY_WANDERER",
  "BABY_WARLOCK",
  "BABY_WIZARD",
  "BARD",
  "BIOLO",
  "BLACKSMITH",
  "CARDINAL",
  "CHAMPION",
  "CLOWN",
  "CREATOR",
  "CRUSADER",
  "CRUSADER2",
  "DANCER",
  "DARK_COLLECTOR",
  "DEATH_KNIGHT",
  "DRAGON_KNIGHT",
  "DRAGON_KNIGHT2",
  "ELEMENTAL_MASTER",
  "GANGSI",
  "GENETIC",
  "GENETIC_2ND",
  "GENETIC_T",
  "GUILLOTINE_CROSS",
  "GUILLOTINE_CROSS_2ND",
  "GUILLOTINE_CROSS_T",
  "GUNSLINGER",
  "GYPSY",
  "HANBOK",
  "HIGH_PRIEST",
  "HIGH_WIZARD",
  "HUNTER",
  "HYPER_NOVICE",
  "IMPERIAL_GUARD",
  "IMPERIAL_GUARD2",
  "INQUISITOR",
  "KAGEROU",
  "KNIGHT",
  "KNIGHT2",
  "LORD_KNIGHT",
  "LORD_KNIGHT2",
  "MAGE",
  "MAGE_HIGH",
  "MECHANIC",
  "MECHANIC2",
  "MECHANIC_2ND",
  "MECHANIC_T",
  "MECHANIC_T2",
  "MEISTER",
  "MEISTER2",
  "MERCHANT",
  "MERCHANT_HIGH",
  "MINSTREL",
  "MINSTREL_2ND",
  "MINSTREL_T",
  "MONK",
  "NIGHT_WATCH",
  "NINJA",
  "NOVICE",
  "NOVICE_HIGH",
  "OBORO",
  "OKTOBERFEST",
  "PALADIN",
  "PALADIN2",
  "PRIEST",
  "PROFESSOR",
  "RANGER",
  "RANGER2",
  "RANGER_2ND",
  "RANGER_T",
  "RANGER_T2",
  "REBELLION",
  "ROGUE",
  "ROYAL_GUARD",
  "ROYAL_GUARD2",
  "ROYAL_GUARD_2ND",
  "ROYAL_GUARD_T",
  "ROYAL_GUARD_T2",
  "RUNE_KNIGHT",
  "RUNE_KNIGHT2",
  "RUNE_KNIGHT_2ND",
  "RUNE_KNIGHT_T",
  "RUNE_KNIGHT_T2",
  "SAGE",
  "SHADOW_CHASER",
  "SHADOW_CHASER_2ND",
  "SHADOW_CHASER_T",
  "SHADOW_CROSS",
  "SHINKIRO",
  "SHIRANUI",
  "SKY_EMPEROR",
  "SKY_EMPEROR2",
  "SNIPER",
  "SORCERER",
  "SORCERER_2ND",
  "SORCERER_T",
  "SOUL_ASCETIC",
  "SOUL_LINKER",
  "SOUL_REAPER",
  "SPIRIT_HANDLER",
  "STALKER",
  "STAR_EMPEROR",
  "STAR_EMPEROR2",
  "STAR_GLADIATOR",
  "STAR_GLADIATOR2",
  "SUMMER",
  "SUMMER2",
  "SUMMONER",
  "SUPER_BABY",
  "SUPER_BABY_E",
  "SUPER_NOVICE",
  "SUPER_NOVICE_E",
  "SURA",
  "SURA_2ND",
  "SURA_T",
  "SWORDMAN",
  "SWORDMAN_HIGH",
  "TAEKWON",
  "THIEF",
  "THIEF_HIGH",
  "TROUBADOUR",
  "TROUVERE",
  "WANDERER",
  "WANDERER_2ND",
  "WANDERER_T",
  "WARLOCK",
  "WARLOCK_2ND",
  "WARLOCK_T",
  "WEDDING",
  "WHITESMITH",
  "WINDHAWK",
  "WINDHAWK2",
  "WIZARD",
  "XMAS",
];

export const RATHENA_JOB_NAME_LOOKUP: CaseInsensitiveLookup = buildCaseInsensitiveLookup(RATHENA_JOB_NAMES);
